language: node_js
node_js:
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"

env:
  - BASE_URL=http://localhost:3000
  - secure: "dT2abzsGEjt+5dtCrCZAEth7clJdUAlQIlnfZDcbHpx5h0pAV0wkZ9w/VxVQCRYoNUf/VY5xAhJsDOKWAeyN9R16D6w9zn0fJ8FX1sE+bJFRFuU+oUDRWFGCYTF1/T9K8nYOQ6IEO9WMP/WJaXiuWwXJpt3jpA/BtWBLjqq/VhJsk+fP2d0aau7p+Cq35ZBDji3ugae9a89E0HkH74V35m1oMmqHd+BWER0XX0YC3uqufzbsGCo8fhOuIYR38VwmiIElTRMiyxawcWo6UsAm2B62NM4rZzEIilaphK8j7g6TeK7hXj8XqE4VKJFf5ENdAJZgV1DGNnu36NTGlfvanaHMvGIrL2BXXsJZiYx/fKGH3BT01Hbux+ODh5t/Y8bGMQS1KQ+iOhw7YGysfp9NUAnCVVV2F6yy5JUsy1OgY5dGegXfbDTpH0lYb+bJbY7FMrXrLSrRRl2ClSk24q3nP70IrfJUK+AsOaSn9iOzV4mMZbEA1ccUIgFtyh3b1HmTbS1zKnsKEcBYdEtu54NVkKy0orf6Ao+Mzj8CNYdV5glwdrhbi5G5FI1W7hkHH6cz8B97XQ14a9fQAk1hS9QHMMSjx65/QSsasoKbm0rTtyoYJtwpMp82Sz/A8/nAcW39u2sKblG7lRSIuYQSFplaYE3vCI3Q6lab4JLvAtyN39U="

deploy:
  provider: heroku
  api_key:
    secure: "EEt2augLYtgaCOMimSpyiRukBZXzTHLkGdpGj3GAPo7Xy1RCUPCT92xu9+/myszUcEMkhGGw5lSsM8scBsd0NM6eL1d89VfjDZMwg0rNp7wIA0FlrB5h/ZXQfZHPIS9Dvcw+vhb4Dk9KGzQQijzU2UdrZOpskiQdsAmnDMFJ3NhkHNUCSJ+at+ObgqVxOQ0GFTs4tn9Sa4yLW+8ETAhBalCJsBDGCNi5xWrFa74ve8ncDNQ2gKiFHPQGVFYtvCY2uanDixXiPtWqfLYJHih0WUwvAtSUO6ACxYuIT+rBU1AjaKs+/02250CnNKQBf7wpO54mm/52UgJcfY0qUKF8Loq99IL9Me6Un2K57M1ckEYvYozOQf64MNPl2sOe3vUU6VWLkK4iKr2IQf1oG8Fc4xXmyrM6S09Rx54fbZ67YhPbPWxvA6NPm/FenYbi6f5HxSv5NucMIOqtuz5Jw9MKJcJvTYdFTK2lI5mXsLNq0JZd4afpK+MKdK4FVt+JCcDvzMVivBx6EW1cTI/bZ35nnuSFdUINNXsHYBO/ut1VF0ipbtcdDli5QyjzfsxOqP8s4eWHxCeqcJ7MiVZxmWTZYtvFdBI3wLdU2gAK4K3SZbvzOZYKdgD78NGLysXyd7imuLYI0DIhasU+UmfcdiPlluj/LdO95XX3Vy8FvSZRQUU="
  app:
    master: melodicsimilarity
    staging: melodicsimilarity-staging
  on:
    repo: freakimkaefig/melodicsimilarity
